### ISSUE TITLE
in run_training, which funtion runs first in thread?

### ISSUE THREAD

**Issue by ouyangzhuzhu** [ebonyclock/deep_rl_vizdoom#11]
HI , here below the code is like this in async_learner.py, and which function runs first? The start() does not assign a function....
     def run_training(self, session):
        self._session = session
        self.start()

and the run_training is called in _async_algo.py below
   for l in learners:
        l.run_training(session)
    for l in learners:
        l.join()

**Comment by mihahauke** [comment]
Learners extend Thread class so 'run' function is executed when the thread is started.

**Comment by ouyangzhuzhu** [comment]
3ks !
