### ISSUE TITLE
AttributeError: module 'networks' has no attribute 'ACLstmNet

### ISSUE THREAD

**Issue by IvanKush** [ebonyclock/deep_rl_vizdoom#3]
start of the **train_a3c.py** gives an error: `AttributeError: module 'networks' has no attribute 'ACLstmNet'`

Need to change `ACLstmNet` to `ACLSTMNet` in the
_settings/defaults/a3c_defaults.yml_

thanks for sharing the code

**Comment by ebonyclock** [comment]
I changed the name of the class instead of yaml. Found some other bug by accident, thanks for the remark.
