### ISSUE TITLE
Healthpack gathering training question

### ISSUE THREAD

**Issue by GoingMyWay** [ebonyclock/deep_rl_vizdoom#6]
Hi @ebonyclock , I am trying to train a healthpack agent with your newest code, after training for a day, I found the performance of the agent is declining.

![image](https://user-images.githubusercontent.com/9346460/28400697-7435a1d0-6d47-11e7-9ccb-9be8b931ce30.png)

And I found the agent was stay in the same place and took action `[1, 1, 0] ` in all the ten episodes. 

I trained it with 

```
$ python3 train_a3c.py -s settings/health_gathering.yml
```

and I tested it with 

```
$ python3 test_a3c.py models/07.19_10-21/ACLstmNet -s settings/health_gathering.yml
```

all with default settings and I changed `[None, 4, 80, 60]` to `[None, 80, 60, 4]` because the `conv2d` can not run in `create_conv_layers()` function in `common.py` if the img_shape is  `[None, 80, 60, 4]`.

here is my diff

```
diff --git a/vizdoom_wrapper.py b/vizdoom_wrapper.py
index 6ac702e..3d286a8 100644
--- a/vizdoom_wrapper.py
+++ b/vizdoom_wrapper.py
@@ -64,7 +64,7 @@ class VizdoomWrapper(object):
         self._reward_scale = reward_scale
 
         self._img_channels = stack_n_frames
-        self.img_shape = (stack_n_frames, resolution[1], resolution[0])
+        self.img_shape = (resolution[1], resolution[0], stack_n_frames)
         # TODO allow continuous actions
         self._actions = [list(a) for a in it.product([0, 1], repeat=len(doom.get_available_buttons()))]
         self.actions_num = len(self._actions)
@@ -99,7 +99,7 @@ class VizdoomWrapper(object):
 
     def _update_screen(self):
         self._current_screen = self.preprocess(self.doom.get_state().screen_buffer)
-        self._current_stacked_screen = np.append(self._current_stacked_screen[1:], self._current_screen, axis=0)
+        self._current_stacked_screen = np.append(self._current_stacked_screen[:, :, 1:], self._current_screen, axis=2)
 
     def _update_misc(self):
         # TODO add support for input_n_actions without game variables
@@ -122,7 +122,7 @@ class VizdoomWrapper(object):
         # img = cv2.resize(img, self._resolution, interpolation=cv2.INTER_NEAREST)
         img = cv2.resize(img, self._resolution, interpolation=cv2.INTER_LINEAR)
         img = img.astype(np.float32) / 255.0
-        img = img.reshape([1] + list(img.shape))
+        img = img.reshape(list(img.shape) + [1])
         return img
 
     def reset(self):
(END)
```

and I removed the `data_format="NCHW"` flag in all the code since it has not been implemented under CPU.

I ran the code on a GPU server with 4 TITAN Xs. 

How long did it cost to train a good agent? And how can I tune all the parameters?  Hope you can help, thank you!

**Comment by GoingMyWay** [comment]
Afer training about 5 hours, the agent got good performance but it still looks like a bit stupid than human.


![image](https://user-images.githubusercontent.com/9346460/28426942-45c06af0-6da7-11e7-85cb-9b042c60f1e2.png)


Now I do not fully know the details of your code, but based on the agent's performance and how agents gather healthpacks, I guess the agent can't see the health pack, it just wanders around the ground to collecting healthpacks.

**Comment by Miffyli** [comment]
Health gathering supreme with its default reward is quite challenging as you get positive reward constantly, no matter what you did (however last time I heard A3C should be able to learn it with sufficient time like you have tried). 

You could try bit of reward shaping to check if the agent learns anything, namely change the reward to be delta-health (and even better: Give +1 reward when player picks up medkit). With this change the agent should start surviving longer inside first hour. My training hardware is in use atm so I can not try this.

**Comment by GoingMyWay** [comment]
@Miffyli , thank you.

I wrongly took `MOVE_LEFT`, `MOVE_RIGHT` as `TURN_LEFT`, `TURN_RIGHT`. And after changed it and add reward shaping and the reward function.

```
   def reward_function(self, picked_delta, episode_step_count):
        health = self.env.get_game_variable(GameVariable.HEALTH)
        if picked_delta == 0:
            # if run out of health before episode ends, give a punishment
            if health < 4 and episode_step_count < self.env.get_episode_timeout():
                reward = -1
            else:
                # alive
                reward = 0.01
        else:
            return picked_delta
        return reward
```

with 32 agents working simultaneously, I got a good performance in about 30 minutes.

![image](https://user-images.githubusercontent.com/9346460/28451820-33f60db8-6e22-11e7-8f9f-030f4ec65f41.png)

**Comment by ebonyclock** [comment]
Sorry for late response. Like @Miffyli said, it's rather a challenging scenario and I am not surprised that vanilla a3c/dqn cannot handle it without shaping.

**Comment by GoingMyWay** [comment]
@ebonyclock , thank you, I have trained a good healthpack gathering agent!
